package:
  name: eagle
  version: "0.9.4.6"

source:
  url: https://pypi.io/packages/source/g/gi-eagle/gi-eagle-{{ PKG_VERSION }}.tar.gz
  sha256: 3b33ed1ef2313ea661c7549a0dffbf1de338df5faf42eef77342a2db47d1467e

build:
  number: 0
  skip: True # [py27 or py35 or py34]
  entry_points:
    - eagle=run:main

requirements:
  host:
    - python
    - setuptools
    - flask
    - numpy
    - scipy
    - h5py
    - pyliftover
    - pysam
    - pybedtools
    - sqt
    - cyvcf2
  run:
    - python
    - flask
    - numpy
    - scipy
    - h5py
    - pyliftover
    - pysam
    - pybedtools
    - sqt
    - cyvcf2

test:
  imports:
    - eagle
    - eagle.core
    - eagle.core.wrap
    - eagle.scripts
    - eagle.tests
    - eagle.views
  commands:
    - eagle --help

about:
  home: https://bitbucket.org/christopherschroeder/eagle
  license: MIT License
  summary: 'Eagle is a webtool for genome variants and snp analysis'
  license_family: MIT

extra:
  recipe-maintainers: 
    - christopher-schroeder
