package:
  name: eagle
  version: "0.9.4.4"

source:
  url: https://pypi.io/packages/source/g/gi-eagle/gi-eagle-{{ PKG_VERSION }}.tar.gz
  sha256: 17b3b4400be1aa4e002c751e8d20dde511ae1a57be461039ec38333845397c0d

build:
  number: 0
  skip: True # [py27]
  entry_points:
    - eagle=run:main

requirements:
  host:
    - python
    - setuptools
    - flask
    - numpy
    - scipy
    - h5py
    - pyliftover
    - pyvcf
  run:
    - python
    - flask
    - numpy
    - scipy
    - h5py
    - pyliftover
    - pyvcf

test:
  imports:
    - eagle
    - eagle.core
    - eagle.core.wrap
    - eagle.scripts
    - eagle.tests
    - eagle.views
  commands:
    - eagle --help

about:
  home: https://bitbucket.org/christopherschroeder/eagle
  license: MIT License
  summary: 'Eagle is a webtool for genome variants and snp analysis'
  license_family: MIT

extra:
  recipe-maintainers: 
    - christopher-schroeder
