{% set version = "1.0.1" %}
{% set build = "0" %}
{% set tarball = "https://bitbucket.org/mroachawri/purge_haplotigs/get/minimap2.tar.gz" %}
{% set sha256 = "ae31483509afb26a8c2100b0c0bc1a066b80d130bbdab06cd55e3c347d22f7c4" %}

package:
  name: purge_haplotigs
  version: '{{ version }}'

source:
  url: '{{ tarball }}'
  sha256: '{{ sha256 }}'

build:
  number: '{{ build }}'

requirements:
  build:
  run:
    - perl >=5.22.0
    - samtools >=1.3.1
    - bedtools >=2.25.0
    - r-base >=3.4.1
    - r-ggplot2 >=2.2.1
    - minimap2 >=2.12
    - mummer4 >=4.0.0beta2
    - make >=4.2.1

test:
  commands:
    - purge_haplotigs help
    - minimap2 -h
    - samtools --help
    - bedtools -h
    - nucmer -h
    - make -h
    - Rscript -e 'require(ggplot2)'
    - perl -e 'use FindBin;use Getopt::Long;use threads;use Thread::Semaphore;use Thread::Queue;use List::Util;'
    

about:
  home: https://bitbucket.org/mroachawri/purge_haplotigs/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pipeline to help with curating heterozygous diploid genome assemblies.
