{% set version = "2.13.0" %}

package:
  name: bioconductor-rgraphviz
  version: {{ version }}
source:
  url: https://bioarchive.galaxyproject.org/Rgraphviz_{{ version }}.tar.gz
  sha256: abe1708886281f05296a2fa9afd806a99a2c05eebd952dc90644b694e9b01c00
build:
  number: 1
  skip: True # [osx]
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-graph
    - r-base
  run:
    - bioconductor-graph
    - r-base
test:
  commands:
    - '$R -e "library(''Rgraphviz'')"'
about:
  home: http://bioconductor.org/packages/release/bioc/html/Rgraphviz.html
  license: EPL
  summary: 'Interfaces R with the AT and T graphviz library for plotting R graph objects
    from the graph package.'

extra:
  identifiers:
    - biotools:rgraphviz
    - doi:10.1038/nmeth.3252
