{% set version = "2.4.14" %}
{% set sha256 = "0c6e466736ac08b2aba28f1ffa4c9f136b3948dcbb61b04a89afcdcf0298307d" %}

package:
  name: igv
  version: "{{ version }}"

source:
  url: "http://data.broadinstitute.org/igv/projects/downloads/{{ version.rsplit('.', 1)[0] }}/IGV_{{ version }}.zip"
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic

requirements:
  run:
    - openjdk >=8.0

test:
  commands:
#    - "igv > log.txt 2>&1 & PID=$! && sleep 2 && kill $PID && grep 'IGV Version {{ version }}' log.txt"

about:
  home: "http://www.broadinstitute.org/software/igv/home"
  license: MIT
  summary: "Integrative Genomics Viewer. Fast, efficient, scalable visualization tool for genomics data and annotations"

extra:
  identifiers:
    - biotools:igv
